name = "DisjointCliqueCover"
uuid = "84c62def-8fae-4380-b7e9-40f47ed17cae"
authors = ["Giulio Burgio <giulioburgio@gmail.com>", "Sergio GÃ³mez <sergio.gomez@urv.cat>", "Joan T. Matamalas <jtmatamalas@protonmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Combinatorics = "0.7, 1.0"
LightGraphs = "1.0, 1.3"
StatsBase = "0.32, 0.33"
julia = "1.2, 1.6"
